version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: ./docker
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
    volumes:
      - $HOME/.ssh:/usr/src/app/.ssh
      - $HOME/.gitconfig:/usr/src/app/.gitconfig
      - $PWD:/usr/src/app

volumes:
  db:
