version: '3'
services:
  web:
    image: node-dashboard
    build: ./docker
    hostname: node-dashboard
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
      - $PWD:/home/node/app
      - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf
