version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_DATABASE: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: ./docker
    command: npm dev
    ports:
      - "3000:3000"
    depends_on:
      - "db"

volumes:
  db:
